@endpoint = http://localhost:3000/api/cars


### get all cars
GET  {{endpoint}} HTTP/3.0
content-type: application/json


### creating a car
POST {{endpoint}} HTTP/1.1
content-type: application/json

{"make": "Toyota", "model": "Camry 2"}

### get non existent car
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

### update a car 
PUT  {{endpoint}}/6ab42cf87de6ac8ecb09ead0 HTTP/3.0
content-type: application/json

{"make": "Toyota", "model": "Camry 2015"}

### delete a car
DELETE  {{endpoint}}/6ab42cf87de6ac8ecb09ead0 HTTP/3.0
content-type: application/json


