@endpoint = http://localhost:3000/api/cars
@dummyEndpoint = http://localhost:3000

###
# @name getAllCars
GET  {{endpoint}} HTTP/3.0
content-type: application/json
x-api-key: blablabla


### creating a car
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json

{"make": "Toyota", "model": "Camry 2022"}

###
@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}}/{{newCar}} HTTP/3.0
Content-Type: application/json

### get non existent car
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

### update a car 
PUT  {{endpoint}}/6ab42cf87de6ac8ecb09ead0 HTTP/3.0
content-type: application/json

{"make": "UPDATED Ford", "model": "Mustang GT"}

### delete a car
DELETE  {{endpoint}}/6ab42cf87de6ac8ecb09ead0 HTTP/3.0
content-type: application/json

# dummy paths
###
GET  {{dummyEndpoint}}/ping HTTP/3.0
content-type: application/json

###
GET  {{dummyEndpoint}}/bananas HTTP/3.0
content-type: application/json

###
GET  {{dummyEndpoint}}/auth HTTP/3.0
content-type: application/json
